Load s3fs ... skip if we already have it:

In [1]:
# pip install s3fs

Enumerate 2019 Yellow Cab files

In [1]:
import s3fs
fs = s3fs.S3FileSystem(anon=True)
trips = fs.ls('nyc-tlc/trip data', detail=True)
files = ['s3://' + trip['Key'] for trip in trips if ('yellow_tripdata_2019' in trip['Key'])]
files

['s3://nyc-tlc/trip data/yellow_tripdata_2019-01.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-02.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-03.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-04.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-05.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-06.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-07.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-08.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-09.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-10.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-11.csv',
 's3://nyc-tlc/trip data/yellow_tripdata_2019-12.csv']

Grab just the first 3

In [3]:
import pandas as pd

In [8]:
%%time

ldf = pd.concat([pd.read_csv(f) for f in files[:3]], ignore_index = True)

CPU times: user 39.8 s, sys: 8.6 s, total: 48.4 s
Wall time: 1min

Get all stat means grouped by pax count

In [10]:
%%time

ldf.groupby("passenger_count").mean()

CPU times: user 1.83 s, sys: 1.56 s, total: 3.39 s
Wall time: 3.39 s

,VendorID,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
passenger_count,,,,,,,,,,,,,,
0,1.003324,2.761346,1.125120,165.401333,164.411817,1.304621,13.824459,1.859814,0.496636,2.032308,0.326346,0.299659,18.841465,1.878968
1,1.608617,2.875634,1.066410,163.829829,162.035006,1.274547,12.761905,0.930748,0.495969,2.077172,0.336432,0.299119,17.761576,1.863058
2,1.647744,2.968769,1.053749,163.212715,161.714965,1.293573,12.901840,0.883311,0.495922,2.069955,0.364396,0.299103,17.979401,1.904779
3,1.715881,2.916267,1.045568,163.021277,161.312050,1.301222,12.708751,0.789976,0.496628,2.027659,0.343784,0.299115,17.729517,1.913564
4,1.678171,2.931118,1.049743,162.949148,160.713654,1.340389,12.845051,0.851139,0.496396,1.939630,0.355138,0.299234,17.806165,1.940089
5,1.994753,2.932267,1.034690,163.226917,161.414318,1.274001,12.536094,0.350460,0.497526,2.116015,0.341589,0.299139,17.640001,1.909028
6,1.993968,2.899518,1.034058,162.694750,161.631794,1.278471,12.446654,0.314401,0.497580,2.086503,0.338724,0.299173,17.453672,1.889221
7,1.921348,2.404157,4.640449,178.696629,195.483146,1.224719,50.382921,0.146067,0.337079,6.712135,1.658090,0.276404,59.962135,0.649351
8,2.000000,4.898000,5.000000,174.760000,160.200000,1.200000,52.671333,0.000000,0.300000,6.318933,2.833867,0.276000,63.333467,1.320755
9,1.893617,3.370213,4.680851,161.531915,168.510638,1.234043,49.997234,0.159574,0.297872,6.070851,2.568936,0.300000,59.820000,0.654762

3 files ~ 70 seconds end-to-end